---
title: Escribiendo buen software
teaching: 15
exercises: 0
questions:
- "¿Cómo puedo escribir software que otras personas puedan usar?"
objectives:
- "Describir las mejores prácticas para escribir software en R y explicar la justificación de cada una."
keypoints:
- "Documenta qué y por qué, no cómo."
- "Divide los programas en funciones cortas de un solo propósito."
- "Escribe pruebas re-ejecutables."
- "No repitas tu código."
- "Se coherente en la nomenclatura, indentación y otros aspectos del estilo."
source: Rmd
---

## Escribir código legible

La parte más importante de escribir código es hacer que sea legible y comprensible.
Quieres que otra persona pueda tener tu código y comprenda lo que hace: la mayoría de las veces, esta persona 
serás tú 6 meses después y si no es comprensible, te estarás culpando por no haber hecho las cosas bien.

## Documentación: dinos qué y por qué, no cómo

Cuando empiezas a programar, tus comentarios a menudo describen lo que hace un comando, ya que aún te 
encuentras en aprendizaje y pueden ayudarte a aclarar conceptos y recordártelos más tarde. Sin embargo, estos 
comentarios no son particularmente útiles, sobre todo cuando no recuerdes qué problema estabas tratando de 
resolver con tu código. Intenta incluir comentarios que te digan *por qué* estás resolviendo un problema 
y *qué* problema es. El *cómo* puede venir después de eso: es un detalle de implementación del que 
idealmente no deberías preocuparte.

## Mantén tu código modular

Nuestra recomendación es que debes separar tus funciones de tus **scripts** y 
almacenarlos en un archivo separado 'source' que llamarás cuando abras la sesión R en tu proyecto. Este enfoque es bueno porque te deja un **script** ordenado y un repositorio de funciones útiles que se pueden cargar en 
cualquier script en tu proyecto. También te permite agrupar funciones relacionadas fácilmente.

## Divide el problema en bocados pequeños

Al principio la resolución de problemas y la escritura de funciones pueden ser tareas que te resulten
desalentadoras debido a la falta de experiencia en programación. Trata de dividir tu problema en bloques digeribles y preocúpate por los detalles de la implementación más adelante. Es recomendable seguir dividiendo el problema en 
funciones cortas de un solo propósito.

## Chequea que tu código está haciendo lo correcto

¡Asegúrate de probar tus funciones!

## No repitas tu código

Las funciones permiten una fácil reutilización dentro de en proyecto. Si identificas bloques de código similares en tu proyecto son en general candidatos a ser convertidos en funciones.

Si tus cálculos se realizan a través de una serie de funciones, entonces 
el proyecto se vuelve más modular y más fácil de cambiar. Este es, especialmente el caso para el cual una entrada particular siempre da una salida particular.

## Recuerda ser elegante

Manten un mismo estilo en todo tu código.


{% include links.md %}
